@startuml agenda
left to right direction

actor "Usuário" as user 

rectangle Agenda {
  usecase "Criar eventos" as criar
  usecase "Editar eventos" as editar
  usecase "Excluir eventos" as excluir 
  usecase "Consultar agenda" as ca
}

user --> criar
user --> editar
user --> excluir
user --> ca
@enduml